"""empty message

Revision ID: 2800cd897083
Revises: c5df849b2b10
Create Date: 2021-03-12 20:37:27.951979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2800cd897083'
down_revision = 'c5df849b2b10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temperature_sensor1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Date', sa.String(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temperature_sensor2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Date', sa.String(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temperature_sensor3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Date', sa.String(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('temperature')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temperature',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('temperature', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='temperature_pkey')
    )
    op.drop_table('temperature_sensor3')
    op.drop_table('temperature_sensor2')
    op.drop_table('temperature_sensor1')
    # ### end Alembic commands ###
