"""empty message

Revision ID: 6977e0ccaf45
Revises: fb5929650536
Create Date: 2021-05-25 21:33:05.770554

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6977e0ccaf45'
down_revision = 'fb5929650536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temperature_sensor1', sa.Column('date', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('temperature_sensor1', 'Date')
    op.add_column('temperature_sensor2', sa.Column('date', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('temperature_sensor2', 'Date')
    op.add_column('temperature_sensor3', sa.Column('date', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('temperature_sensor3', 'Date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temperature_sensor3', sa.Column('Date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('temperature_sensor3', 'date')
    op.add_column('temperature_sensor2', sa.Column('Date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('temperature_sensor2', 'date')
    op.add_column('temperature_sensor1', sa.Column('Date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('temperature_sensor1', 'date')
    # ### end Alembic commands ###
