<<<<<<< HEAD
"""empty message

Revision ID: fb5929650536
Revises: 2800cd897083
Create Date: 2021-05-25 05:07:47.202354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb5929650536'
down_revision = '2800cd897083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('temperature_sensor1', 'Date',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('temperature_sensor2', 'Date',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('temperature_sensor3', 'Date',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('temperature_sensor3', 'Date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('temperature_sensor2', 'Date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('temperature_sensor1', 'Date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
=======
"""empty message

Revision ID: fb5929650536
Revises: 
Create Date: 2021-05-25 21:32:44.640940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb5929650536'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    pass


def downgrade():
    pass
>>>>>>> e8b10cfd35497fe50e5f0edfb82c639e28ede3b0
